### ISSUE TITLE
Label quality varies 2 much

### ISSUE THREAD

**Issue by Godricly** [andreasveit/coco-text#11]
Hi,
  Is there any plan to release a better label for training set? The quality of current one varies too much.  Some polygons are exactly same as bbox for oriented text. This is really annoying. 
Thanks

some example images with typical issues
COCO_train2014_000000294914.jpg  2 different polygons covers same text differently
COCO_train2014_000000262184.jpg  The polygon cant convers the text 
COCO_train2014_000000131174.jpg  It seems that a region is mislabeled

**Comment by andreasveit** [comment]
Hi Godricly,
Thanks for the interest in the dataset.

There is indeed a plan to release a V2 of the dataset with significantly improved polygons this fall.

Further, note that the polygon annotations are incomplete and should be considered in its alpha phase. The competition only evaluates bounding boxes.
