### ISSUE TITLE
about icdar 2017 cocotext task2 Cropped words dataset

### ISSUE THREAD

**Issue by xinghedyc** [andreasveit/coco-text#12]
I don't understand why there is a '|' in the annotation file such as "1221677,|EBB,| " , but I can't see a '|' in the corresponding image?

**Comment by andreasveit** [comment]
Hi xinghedyc,
Thanks for the interest in the dataset.

There are indeed a few annotations which need improvement.
Could you please email me the specific annotation and image id?
Thanks,
Andreas
