### ISSUE TITLE
Problems occurred when running ct.showAnns(anns)

### ISSUE THREAD

**Issue by SharonZhu** [andreasveit/coco-text#13]
Hi, I have run this API on my Mac OS and everything went right until problems occurred after the line ct.showAnns(anns).
The warning is as follows:
![image](https://user-images.githubusercontent.com/28685102/27946442-611824d8-6324-11e7-854c-40846d44039a.png)

And the result of this line is:
![image](https://user-images.githubusercontent.com/28685102/27946481-9f22f6ae-6324-11e7-9d4b-f5e89237475e.png)

Is there something wrong with this code or my computer?

**Comment by andreasveit** [comment]
Looks like it is not an issue with this code, but rather a system issue.
