### ISSUE TITLE
multi-oriented detection evaluation?

### ISSUE THREAD

**Issue by xinghedyc** [andreasveit/coco-text#14]
Hi, may I ask obout multi-oriented detection evaluation? Do you provide evaluation method based on polygon predictions? such as (x1,y1,x2,y2,x3,y3,x4,y4)

**Comment by andreasveit** [comment]
Hi xinghedyc,
Thanks for the interest in the dataset.

There is a plan to release a V2 of the dataset with significantly improved polygons this fall.
With that release, we also plan to provide a multi-oriented detection evaluation.
