### ISSUE TITLE
Cant find coco_text.json annotation file?

### ISSUE THREAD

**Issue by arsalan993** [andreasveit/coco-text#18]
I downloaded this zip file 
[2014 Train/Val annotations 241MB](http://images.cocodataset.org/annotations/annotations_trainval2014.zip)
from the http://cocodataset.org/#download but i am unable to find the required COCO_Text file in the given folder.

**Comment by andreasveit** [comment]
Thank you for your interest in our work.
For information on the dataset and links to the annotations, please refer to the dataset website:
https://vision.cornell.edu/se3/coco-text-2/
Hope that is helpful.
