### ISSUE TITLE
Can you please revisit the whole procedure on how to setup your code?

### ISSUE THREAD

**Issue by arsalan993** [andreasveit/coco-text#19]
Since i believe contents on the links that you have provided has changes ..  kindly provide the appropriate links or if data not available the kindly upload data on a cloud so that we down it. 

Thanks

**Comment by andreasveit** [comment]
Thank you for the feedback. For now, please refer to the dataset website (https://vision.cornell.edu/se3/coco-text-2/) for details on the data and setup.
