### ISSUE TITLE
Which dataset i should download for COCO-Text annotations 2017 v1.4?

### ISSUE THREAD

**Issue by arsalan993** [andreasveit/coco-text#20]
https://vision.cornell.edu/se3/coco-text-2/
http://cocodataset.org/#download

**Comment by arsalan993** [comment]
i am confused between which year of data for this version of annotations and whether this annotations are for train or val or for both..
Which year dataset i should download 2014 or 2015 or 2017

**Comment by andreasveit** [comment]
All COCO-Text images are part of **2014 COCO Train images**

**Comment by Giribushan** [comment]
Man there is no link to download dataset..what a stupid website..really frustrated.!!
