### ISSUE TITLE
Regarding v1's polygon vs v2's mask

### ISSUE THREAD

**Issue by mustardlove** [andreasveit/coco-text#25]
Hello
Thank you for great source
I have one question! 

In cocotext version1, you have code in showAnn() in coco_text.py
`tl_x, tl_y, tr_x, tr_y, br_x, br_y, bl_x, bl_y = ann['polygon']`
So polygon information is fixed in length (8)

On the other hand, in https://github.com/bgshih/coco-text/blob/master/coco_text.py showAnn(),
`verts = list(zip(*[iter(ann['mask'])] * 2)) + [(0, 0)]`
which means mask annotation has different lengths per box

Could you explain what this difference mean?

**Comment by andreasveit** [comment]
I suggest using the V2 of the dataset.
