### ISSUE TITLE
Regarding adding a Colab Notebook

### ISSUE THREAD

**Issue by sayakpaul** [andreasveit/coco-text#28]
Hi @andreasveit. 

I created a [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/05a641f60300f0d7f1bf74ffe0b28b87/coco_text_demo.ipynb) in order for folks to visualize the COCO-text dataset more easily and readily. Would you like me to create a PR that includes this Colab Notebook?

**Comment by andreasveit** [comment]
Thanks @sayakpaul, this looks good. Yes please add it.
