### ISSUE TITLE
About 1000 test annotation 

### ISSUE THREAD

**Issue by kaiyuyue** [andreasveit/coco-text#6]
Hi, where can find the test annotations? In json files, there has only train set and val set. In ICDAR2017 official page, it says '1000 val and 1000 test'. Should I break the 2000 val into two part and change the json file by myself?

BTW: there has some kind of spelling errors in the code file and official page: some words of 'illegible' are spelled in 'illegilbe'. 
https://github.com/andreasveit/coco-text/blob/master/coco_text_Demo.ipynb 
and the official site https://vision.cornell.edu/se3/coco-text/

**Comment by andreasveit** [comment]
Thanks for the interest.
The official annotations and split for the competition will be uploaded early next week.

**Comment by kaiyuyue** [comment]
OK~thanks, I get that.
