### ISSUE TITLE
Missing annotations

### ISSUE THREAD

**Issue by dubvulture** [andreasveit/coco-text#8]
This is not really a problem related to the API but rather to [COCO_Text.json](https://s3.amazonaws.com/cocotext/COCO_Text.zip)
I didn't know where to report this looking on the [website](https://vision.cornell.edu/se3/coco-text/ ) so here I am.

While running coco_evaluation.getDetections() this is what happened:
```python
gt_box = groundtruth.anns[gt_box_id['bbox']
KeyError: 1218650
```
The same holds for coco_evaluation.evaluateEndToEnd()

This is due to non-existent annotations referenced in **imgToAnns**.

Am I missing something or this is a real problem in the json file?

**Comment by andreasveit** [comment]
Hi dubvulture,
Thanks for pointing out the issue.
A new version 1.3 of the dataset has been uploaded to: https://s3.amazonaws.com/cocotext/COCO_Text.zip 
Best,
Andreas
